version: '3'

networks:
  mynet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.2.0.0/16

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 80:80 # Troque a porta caso seja necessário
      - 443:443
    volumes:
      - .:/var/www/html
    links:
      - mysql:mysql
    networks:
      mynet:
        ipv4_address: 10.2.0.2

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql/
    environment:
      - MYSQL_DATABASE=phprs
      - MYSQL_ROOT_PASSWORD=jeff
      - MYSQL_USER=jprogram
      - MYSQL_PASSWORD=jeff
    networks:
      mynet:
        ipv4_address: 10.2.0.3

volumes:
  mysql:
