version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 80:80 # Troque a porta caso seja necessário
      - 443:443
    volumes:
      - .:/var/www/html
    links:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: 'phprs'
      MYSQL_USER: 'jprogram'
      MYSQL_PASSWORD: 'jeff'

volumes:
  mysql:
